{
 "cells": [
  {
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-04-21T11:32:53.426807Z",
     "start_time": "2025-04-21T11:30:22.452660Z"
    }
   },
   "cell_type": "code",
   "source": [
    "#The Quizzical Labyrinth - A game in python by Rachel Weller\n",
    "# Some parts of this game were created with the assistance of ChatGPT by OpenAI\n",
    "import time\n",
    "\n",
    "print(\"\"\"\n",
    "            (Welcome To The Labyrinth)\n",
    "    ^     °  (Enter ONLY If you DARE)\n",
    "   / \\\\ °\n",
    "  /___\\\\\n",
    "  (°~°)  *\n",
    "  / * \\\\ |\n",
    " /(   )\\\\|\n",
    "  || ||\n",
    "  () ()\n",
    "\"\"\")\n",
    "\n",
    "print(\"\\\"Welcome to our little labyrinth, throughout your journey you will encounter many a strange thing.\\\"\")\n",
    "print(\"\\\"But don’t you worry we do a thorough sweep of the labyrinth at the end of they day. So should you get lost and lose all hope hunker down and wait for nightfall.\\\"\")\n",
    "print(\"\\\"Ah, I see you bought our little sack pack for your journey for the low price of 9,99$. Comes with one flashlight, an energy bar and a flask of boiling hot sewage. Should it come to it you can feed the energy bar to our complimentary gigantic earth worms.\\\"\")\n",
    "time.sleep(15) #15 second pause\n",
    "print(\"\\\"How are we feeling?\\\"\") #First question\n",
    "print(\"\")\n",
    "\n",
    "time.sleep(5)#5 second pause\n",
    "print(\"1: Amazing, I can’t wait to go in!\")\n",
    "print(\"2: Why would I need a flask of boiling hot sewage?\")\n",
    "\n",
    "time.sleep(10) #10 second pause\n",
    "try:\n",
    "    answer = int(input(\"How are we feeling?\"))\n",
    "    if answer ==1:\n",
    "        print(\"\\\"Let’s get going then, I love your enthusiasm. I do hope you make it. Off you go now!\\\"\")\n",
    "    elif answer ==2:\n",
    "        print(\"\\\"What’s the sewage for you ask? Well, we can’t give you all the answers, can we? Let’s get going! Off you go now, I hope to see you on the other side!\\\"\")\n",
    "    else:\n",
    "        print(\"\\\"I see you're more the silent type... Well off you go then!\\\"\")\n",
    "except ValueError:\n",
    "    print(\"Please enter a valid number!\")\n",
    "\n",
    "\n",
    "time.sleep(10)\n",
    "print(\"\"\"\n",
    "       _________\n",
    "      |  _____  |\n",
    "      | |  |  | |\n",
    "      | |__|__| |\n",
    "      |      _| |\n",
    "      |         |\n",
    "      |         |\n",
    "    _______________\n",
    "\"\"\")\n",
    "time.sleep(5)\n",
    "print(\"You enter the labyrinth, as soon as you step over the threshold an unsettling quiet comes over you.  Slowly you take a few steps towards the first crossroad.\")\n",
    "\n",
    "print(\"\")\n",
    "print(\"You now have two options:1. Left or 2. Right?\")\n",
    "print(\"\")\n",
    "time.sleep(5)\n",
    "\n",
    "while True:\n",
    "    try:\n",
    "        question = int(input(\"Will you go 1. Left or 2. Right?\"))\n",
    "        if question == 1:\n",
    "            print(\"After turning left you see a patch of haze ahead of you, I seems to be slowly creeping towards you. Still, it doesn't seem threatening, more like it is trying to show you something…\")\n",
    "            #Path A begins\n",
    "\n",
    "            print(\"As you stand in front of the patch of haze it seems to be calling to you, its glow pulling you in\")\n",
    "            print(\"What do you do?\")\n",
    "            print(\"\")\n",
    "            print(\"1. I make my way towards the patch of haze.\")\n",
    "            print(\"2. Let me think this through before I make a decision.\")\n",
    "            time.sleep(10)\n",
    "            follow_haze = input(\"Choose 1 or 2:\")\n",
    "            #Path A go through haze\n",
    "            time.sleep(5)\n",
    "            if follow_haze == \"1\":\n",
    "                print(\"The closer I get the more my teeth start to chatter and I feel myself shivering. Oh no, I’ve made a mistake haven’t I. Will I ever be warm again?\")\n",
    "                #Path A.1\n",
    "                print(\"Quickly now, you can either stumble back towards the entrance and wait to be rescued, or try and find a way out of this, what do you do? \")\n",
    "                print(\"1. I stumble back towards the entrance and await my rescuers shivering and cursing my foolish nature\")\n",
    "                exit()\n",
    "                print(\"2. I will try and persevere!\")\n",
    "\n",
    "                time.sleep(15)\n",
    "\n",
    "                try:\n",
    "                    haze_choice = input(\"What do you do?\")\n",
    "                    if haze_choice == \"1\":\n",
    "                        print(\"This journey has ended for you\")\n",
    "                        exit()\n",
    "                    elif haze_choice == \"2\":\n",
    "                        print(\"Huzzah! The boiling hot sewage, of course! I pull out my flask and fuelled by the hot steam I make my way through the patch of haze. \")\n",
    "                    else:\n",
    "                        print(\"You have hesitated for too long and the cold overwhelms you. Lets hope those giant worms dont find you...\")\n",
    "                        exit()\n",
    "                except ValueError:\n",
    "                    print(\"Please enter a valid number. Either 1 for left or 2 for Right.\")\n",
    "            elif follow_haze == \"2\":\n",
    "                        print(\"As you take a moment to think you see that the hedged around the patch of haze have frozen solid, and is that a squirrel lying there, frozen solid?\")\n",
    "                        print(\"What can I do?\")\n",
    "                        print(\"Huzzah! The boiling hot sewage, of course! I pull out my flask and fuelled by the hot steam I make my way through the patch of haze.\")\n",
    "            else:\n",
    "                print(\"You are trapped in the haze while you hesitated... lets hope those rescuers find you before the worms...\")\n",
    "                exit()\n",
    "\n",
    "           #Path B\n",
    "        elif question == 2:\n",
    "            print(\"After turning right you see a hooded figure emerge from the shadows, as you turn to look behind you you see the way behind has turned into a dead end. You must go on! The hooded figure glides towards you, but before you can react it opens its mouth and starts to speak…\")\n",
    "            print(\"Hello there traveler, don’t you worry all you must do to cross my path and emerge victorious is to answer this simple question. What grows smaller the older it gets? \")\n",
    "            time.sleep(20)\n",
    "            hooded_figure = int(input(\"What grows smaller the older it gets?\"))\n",
    "            if hooded_figure == \"candle\":\n",
    "                print(\"Very good, very adept you are. Off you go now.\")\n",
    "            else:\n",
    "                print(\"Well, well, well... looks like you'll be needing that flashlight sooner than you thought.\")\n",
    "                print(\"Everything goes dark and the next thing you know you are being carried out of the labyrinth on a stretcher.\")\n",
    "                exit()\n",
    "            time,sleep(10)\n",
    "\n",
    "        else:\n",
    "          print(\"You must choose. The entrance to the labyrinth is long gone, only left or right remains\")\n",
    "    except ValueError:\n",
    "            print(\"Please enter a valid number. Either 1 for left or 2 for Right.\")\n",
    "\n",
    "    #Next path for both A and B\n",
    "    print(\"As you continue on you walk towards a crossroads\")\n",
    "    print(\"Do you go straight ahead, left or right?\")\n",
    "    print(\"1. I choose the left path.\")\n",
    "    print(\"2. I choose the right path.\")\n",
    "    print(\"3. I go straight ahead\")\n",
    "    time.sleep(10)\n",
    "    try:\n",
    "        crossroads =int(input(\"Do you go straight ahead, left or right?\"))\n",
    "        if crossroads == \"1\":\n",
    "            print(\"There is nothing here, oh no where did my exit go\")\n",
    "            exit()\n",
    "        elif crossroads == \"2\":\n",
    "            print(\"You walk along the path and come upon a small child. You briefly wonder if child labour laws apply in mystical labyrinths before getting on with it.\")\n",
    "            print(\"The child looks up at you and smiles, holding up five little bottles, gesturing for you to choose one. As everyone knows refusing would be considered incredibly rude so don’t you even think about it.\")\n",
    "            time.sleep(10)\n",
    "            try:\n",
    "                choose_bottle = int(input(\"Choose a bottle (1-5):\"))\n",
    "                if choose_bottle == 1:\n",
    "                    print(\"Uhh is this Sprite™?\")\n",
    "                elif choose_bottle == 2:\n",
    "                    print(\"Uhh is this a Coke Zero™?\")\n",
    "                elif choose_bottle == 3:\n",
    "                    print(\"Uhh is this sparkling water?\")\n",
    "                elif choose_bottle == 4:\n",
    "                    print(\"Uhh is this Fanta™\")\n",
    "                elif choose_bottle == 5:\n",
    "                    print(\"Oh, this one is empty...\")\n",
    "                else:\n",
    "                    print(\"I see someone is feeling rude today...\")\n",
    "                    print(\"Well, that is not how this game goes. Why is it going dark, you ask?\")\n",
    "                    print(\"The journey has ended for you.\")\n",
    "                    exit()\n",
    "                print(\"The child giggles and lets you pass before running ahead and disappearing.\")\n",
    "            except ValueError:\n",
    "                print(\"That wasn't a number! The child frowns at you.\")\n",
    "                print(\"The shadows close in.\")\n",
    "                print(\"The journey has ended for you\")\n",
    "                exit()\n",
    "\n",
    "        elif crossroads == \"3\":\n",
    "            print(\"There is nothing here, oh no where did my exit go?\")\n",
    "            exit()\n",
    "        else:\n",
    "            print(\"You must choose a path!\")\n",
    "    except ValueError:\n",
    "            print(\"Please enter a valid number!\")\n",
    "\n",
    "    time.sleep(5)\n",
    "    #Step 3:\n",
    "    print(\"As you continue dusk starts to creep in and all of a sudden all you can see are numbers floating in front of you. \")\n",
    "    time.sleep(10)\n",
    "    print(\"A deep voice, ask you “What are the first four digits of pi?\")\n",
    "    time.sleep(10)\n",
    "    first =input(\"What is the first digit\")\n",
    "    if first != \"3\":\n",
    "        print(\"Someone has not been paying attention.\")\n",
    "        print(\"This journey has ended for you.\")\n",
    "        exit()\n",
    "\n",
    "    second = input(\"What is the second digit\")\n",
    "    if second != \"1\":\n",
    "        print(\"Someone has not been paying attention.\")\n",
    "        print(\"This journey has ended for you.\")\n",
    "        exit()\n",
    "\n",
    "    third = input(\"What is the third digit?\")\n",
    "    if third != \"4\":\n",
    "        print(\"Someone has not been paying attention.\")\n",
    "        print(\"This journey has ended for you.\")\n",
    "        exit()\n",
    "\n",
    "    fourth = input(\"What is the fourth digit?\")\n",
    "    if fourth != \"1\":\n",
    "        print(\"Someone has not been paying attention.\")\n",
    "        print(\"This journey has ended for you.\")\n",
    "        exit()\n",
    "\n",
    "    print(\"Good job, you. The numbers slowly fade away and you make your way forward.\")\n",
    "    time.sleep(10)\n",
    "    print(\"\")\n",
    "    print(\"As your legs start to feel heavy you look up and see a light ahead.\")\n",
    "    print(\"Eureka!\")\n",
    "    print(\"You’ve finally made it out of here.\")\n",
    "    print(\"\")\n",
    "    time.sleep(5)\n",
    "    print(\"Unless what is that oh no a series of true or false questions are shooting at you.\")\n",
    "    print(\"(Yes, you read that right, ever heard of question bullets?)\")\n",
    "    print(\"(No, well now you have.)\")\n",
    "    print(\"\")\n",
    "    time.sleep(2)\n",
    "    #check answers\n",
    "    def ask_questions(questions, correct_answer):\n",
    "        print(questions)\n",
    "        answer = input(\"A or B\").strip().upper()\n",
    "        print(\"Lets take a look at that...\")\n",
    "        time.sleep(2)\n",
    "        if answer != correct_answer.upper():\n",
    "            print(\"That was wrong, bad luck, looks like you just missed the exit. Have fun in the dark. Your journey has ended here\")\n",
    "            exit()\n",
    "        else:\n",
    "            print(\"Very well, here is your next question...\")\n",
    "            time.sleep(1)\n",
    "    #questions\n",
    "    ask_questions(\"More people die from vending machines than from sharks. \\nA. True \\nB. False\", \"A\")\n",
    "    print(\"\")\n",
    "    ask_questions(\"The earth is round. \\nA. True \\nB. False\", \"A\")\n",
    "    print(\"\")\n",
    "    ask_questions(\"The moon landing was fake. \\nA. True \\nB. False\", \"B\")\n",
    "    print(\"\")\n",
    "    ask_questions(\"Alexander Hamilton was the first president of the United States of America. \\nA. True \\nB. False\", \"B\")\n",
    "    print(\"\")\n",
    "    ask_questions(\"The biggest animal in the world is the blue whale. \\nA. True \\nB. False\", \"A\")\n",
    "    print(\"\")\n",
    "    ask_questions(\"There are six world wonders. \\nA. True \\nB. False\", \"B\")\n",
    "    print(\"\")\n",
    "    time.sleep(5)\n",
    "    print(\"\\\"Look at you smarty pants you’ve made it past the last challenge and have successfully found the exit\\\"\")\n",
    "    print(\"\"\"\n",
    "            (Welcome Back From The Labyrinth!)\n",
    "    ^     °\n",
    "   / \\\\ °\n",
    "  /___\\\\\n",
    "  (°~°)  *\n",
    "  / * \\\\ |\n",
    " /(   )\\\\|\n",
    "  || ||\n",
    "  () ()\n",
    "   \"\"\")\n",
    "    time.sleep(5)\n",
    "    print(\"\\\"Would you like to purchase some pictures we took during your bravest moments?\\\"\")\n",
    "    print(\"\\\"Only 29,99$?\\\"\")\n",
    "    time.sleep(3)\n",
    "    print(\"\\\"No? Why didn’t I warn you about the labyrinth?\\\"\")\n",
    "    print(\"\\\"Well that would have ruined the surprise… Anyway have a great day, come again.\\\"\")\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ],
   "id": "917eceefe4d27472",
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "            (Welcome To The Labyrinth)\n",
      "    ^     °  (Enter ONLY If you DARE)\n",
      "   / \\ °\n",
      "  /___\\\n",
      "  (°~°)  *\n",
      "  / * \\ |\n",
      " /(   )\\|\n",
      "  || ||\n",
      "  () ()\n",
      "\n",
      "\"Welcome to our little labyrinth, throughout your journey you will encounter many a strange thing.\"\n",
      "\"But don’t you worry we do a thorough sweep of the labyrinth at the end of they day. So should you get lost and lose all hope hunker down and wait for nightfall.\"\n",
      "\"Ah, I see you bought our little sack pack for your journey for the low price of 9,99$. Comes with one flashlight, an energy bar and a flask of boiling hot sewage. Should it come to it you can feed the energy bar to our complimentary gigantic earth worms.\"\n",
      "\"How are we feeling?\"\n",
      "\n",
      "1: Amazing, I can’t wait to go in!\n",
      "2: Why would I need a flask of boiling hot sewage?\n",
      "\"Let’s get going then, I love your enthusiasm. I do hope you make it. Off you go now!\"\n",
      "\n",
      "       _________\n",
      "      |  _____  |\n",
      "      | |  |  | |\n",
      "      | |__|__| |\n",
      "      |      _| |\n",
      "      |         |\n",
      "      |         |\n",
      "    _______________\n",
      "\n",
      "You enter the labyrinth, as soon as you step over the threshold an unsettling quiet comes over you.  Slowly you take a few steps towards the first crossroad.\n",
      "\n",
      "You now have two options:1. Left or 2. Right?\n",
      "\n",
      "After turning right you see a hooded figure emerge from the shadows, as you turn to look behind you you see the way behind has turned into a dead end. You must go on! The hooded figure glides towards you, but before you can react it opens its mouth and starts to speak…\n",
      "Hello there traveler, don’t you worry all you must do to cross my path and emerge victorious is to answer this simple question. What grows smaller the older it gets? \n",
      "Please enter a valid number. Either 1 for left or 2 for Right.\n",
      "As you continue on you walk towards a crossroads\n",
      "Do you go straight ahead, left or right?\n",
      "1. I choose the left path.\n",
      "2. I choose the right path.\n",
      "3. I go straight ahead\n",
      "You must choose a path!\n",
      "As you continue dusk starts to creep in and all of a sudden all you can see are numbers floating in front of you. \n",
      "A deep voice, ask you “What are the first four digits of pi?\n",
      "Good job, you. The numbers slowly fade away and you make your way forward.\n",
      "As your legs start to feel heavy you look up and see a light ahead.\n",
      "Eureka!\n",
      "You’ve finally made it out of here.\n",
      "Unless what is that oh no a series of true or false questions are shooting at you.\n",
      "(Yes, you read that right, ever heard of question bullets?)\n",
      "(No, well now you have.)\n",
      "More people die from vending machines than from sharks. \n",
      "A. True \n",
      "B. False\n",
      "Lets take a look at that...\n",
      "That was wrong, bad luck, looks like you just missed the exit. Have fun in the dark. Your journey has ended here\n",
      "The earth is round. \n",
      "A. True \n",
      "B. False\n",
      "Lets take a look at that...\n",
      "Very well, here is your next question...\n",
      "The moon landing was fake. \n",
      "A. True \n",
      "B. False\n",
      "Lets take a look at that...\n",
      "Very well, here is your next question...\n",
      "Alexander Hamilton was the first president of the United States of America. \n",
      "A. True \n",
      "B. False\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "Interrupted by user",
     "output_type": "error",
     "traceback": [
      "\u001B[31m---------------------------------------------------------------------------\u001B[39m",
      "\u001B[31mKeyboardInterrupt\u001B[39m                         Traceback (most recent call last)",
      "\u001B[36mCell\u001B[39m\u001B[36m \u001B[39m\u001B[32mIn[1]\u001B[39m\u001B[32m, line 225\u001B[39m\n\u001B[32m    223\u001B[39m ask_questions(\u001B[33m\"\u001B[39m\u001B[33mThe earth is round. \u001B[39m\u001B[38;5;130;01m\\n\u001B[39;00m\u001B[33mA. True \u001B[39m\u001B[38;5;130;01m\\n\u001B[39;00m\u001B[33mB. False\u001B[39m\u001B[33m\"\u001B[39m, \u001B[33m\"\u001B[39m\u001B[33mA\u001B[39m\u001B[33m\"\u001B[39m)\n\u001B[32m    224\u001B[39m ask_questions(\u001B[33m\"\u001B[39m\u001B[33mThe moon landing was fake. \u001B[39m\u001B[38;5;130;01m\\n\u001B[39;00m\u001B[33mA. True \u001B[39m\u001B[38;5;130;01m\\n\u001B[39;00m\u001B[33mB. False\u001B[39m\u001B[33m\"\u001B[39m, \u001B[33m\"\u001B[39m\u001B[33mB\u001B[39m\u001B[33m\"\u001B[39m)\n\u001B[32m--> \u001B[39m\u001B[32m225\u001B[39m \u001B[43mask_questions\u001B[49m\u001B[43m(\u001B[49m\u001B[33;43m\"\u001B[39;49m\u001B[33;43mAlexander Hamilton was the first president of the United States of America. \u001B[39;49m\u001B[38;5;130;43;01m\\n\u001B[39;49;00m\u001B[33;43mA. True \u001B[39;49m\u001B[38;5;130;43;01m\\n\u001B[39;49;00m\u001B[33;43mB. False\u001B[39;49m\u001B[33;43m\"\u001B[39;49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[33;43m\"\u001B[39;49m\u001B[33;43mB\u001B[39;49m\u001B[33;43m\"\u001B[39;49m\u001B[43m)\u001B[49m\n\u001B[32m    226\u001B[39m ask_questions(\u001B[33m\"\u001B[39m\u001B[33mThe biggest animal in the world is the blue whale. \u001B[39m\u001B[38;5;130;01m\\n\u001B[39;00m\u001B[33mA. True \u001B[39m\u001B[38;5;130;01m\\n\u001B[39;00m\u001B[33mB. False\u001B[39m\u001B[33m\"\u001B[39m, \u001B[33m\"\u001B[39m\u001B[33mA\u001B[39m\u001B[33m\"\u001B[39m)\n\u001B[32m    227\u001B[39m ask_questions(\u001B[33m\"\u001B[39m\u001B[33mThere are six world wonders. \u001B[39m\u001B[38;5;130;01m\\n\u001B[39;00m\u001B[33mA. True \u001B[39m\u001B[38;5;130;01m\\n\u001B[39;00m\u001B[33mB. False\u001B[39m\u001B[33m\"\u001B[39m, \u001B[33m\"\u001B[39m\u001B[33mB\u001B[39m\u001B[33m\"\u001B[39m)\n",
      "\u001B[36mCell\u001B[39m\u001B[36m \u001B[39m\u001B[32mIn[1]\u001B[39m\u001B[32m, line 212\u001B[39m, in \u001B[36mask_questions\u001B[39m\u001B[34m(questions, correct_answer)\u001B[39m\n\u001B[32m    210\u001B[39m \u001B[38;5;28;01mdef\u001B[39;00m\u001B[38;5;250m \u001B[39m\u001B[34mask_questions\u001B[39m(questions, correct_answer):\n\u001B[32m    211\u001B[39m     \u001B[38;5;28mprint\u001B[39m(questions)\n\u001B[32m--> \u001B[39m\u001B[32m212\u001B[39m     answer = \u001B[38;5;28;43minput\u001B[39;49m\u001B[43m(\u001B[49m\u001B[33;43m\"\u001B[39;49m\u001B[33;43mA or B\u001B[39;49m\u001B[33;43m\"\u001B[39;49m\u001B[43m)\u001B[49m.strip().upper()\n\u001B[32m    213\u001B[39m     \u001B[38;5;28mprint\u001B[39m(\u001B[33m\"\u001B[39m\u001B[33mLets take a look at that...\u001B[39m\u001B[33m\"\u001B[39m)\n\u001B[32m    214\u001B[39m     time.sleep(\u001B[32m2\u001B[39m)\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\kernelbase.py:1282\u001B[39m, in \u001B[36mKernel.raw_input\u001B[39m\u001B[34m(self, prompt)\u001B[39m\n\u001B[32m   1280\u001B[39m     msg = \u001B[33m\"\u001B[39m\u001B[33mraw_input was called, but this frontend does not support input requests.\u001B[39m\u001B[33m\"\u001B[39m\n\u001B[32m   1281\u001B[39m     \u001B[38;5;28;01mraise\u001B[39;00m StdinNotImplementedError(msg)\n\u001B[32m-> \u001B[39m\u001B[32m1282\u001B[39m \u001B[38;5;28;01mreturn\u001B[39;00m \u001B[38;5;28;43mself\u001B[39;49m\u001B[43m.\u001B[49m\u001B[43m_input_request\u001B[49m\u001B[43m(\u001B[49m\n\u001B[32m   1283\u001B[39m \u001B[43m    \u001B[49m\u001B[38;5;28;43mstr\u001B[39;49m\u001B[43m(\u001B[49m\u001B[43mprompt\u001B[49m\u001B[43m)\u001B[49m\u001B[43m,\u001B[49m\n\u001B[32m   1284\u001B[39m \u001B[43m    \u001B[49m\u001B[38;5;28;43mself\u001B[39;49m\u001B[43m.\u001B[49m\u001B[43m_parent_ident\u001B[49m\u001B[43m[\u001B[49m\u001B[33;43m\"\u001B[39;49m\u001B[33;43mshell\u001B[39;49m\u001B[33;43m\"\u001B[39;49m\u001B[43m]\u001B[49m\u001B[43m,\u001B[49m\n\u001B[32m   1285\u001B[39m \u001B[43m    \u001B[49m\u001B[38;5;28;43mself\u001B[39;49m\u001B[43m.\u001B[49m\u001B[43mget_parent\u001B[49m\u001B[43m(\u001B[49m\u001B[33;43m\"\u001B[39;49m\u001B[33;43mshell\u001B[39;49m\u001B[33;43m\"\u001B[39;49m\u001B[43m)\u001B[49m\u001B[43m,\u001B[49m\n\u001B[32m   1286\u001B[39m \u001B[43m    \u001B[49m\u001B[43mpassword\u001B[49m\u001B[43m=\u001B[49m\u001B[38;5;28;43;01mFalse\u001B[39;49;00m\u001B[43m,\u001B[49m\n\u001B[32m   1287\u001B[39m \u001B[43m\u001B[49m\u001B[43m)\u001B[49m\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\kernelbase.py:1325\u001B[39m, in \u001B[36mKernel._input_request\u001B[39m\u001B[34m(self, prompt, ident, parent, password)\u001B[39m\n\u001B[32m   1322\u001B[39m \u001B[38;5;28;01mexcept\u001B[39;00m \u001B[38;5;167;01mKeyboardInterrupt\u001B[39;00m:\n\u001B[32m   1323\u001B[39m     \u001B[38;5;66;03m# re-raise KeyboardInterrupt, to truncate traceback\u001B[39;00m\n\u001B[32m   1324\u001B[39m     msg = \u001B[33m\"\u001B[39m\u001B[33mInterrupted by user\u001B[39m\u001B[33m\"\u001B[39m\n\u001B[32m-> \u001B[39m\u001B[32m1325\u001B[39m     \u001B[38;5;28;01mraise\u001B[39;00m \u001B[38;5;167;01mKeyboardInterrupt\u001B[39;00m(msg) \u001B[38;5;28;01mfrom\u001B[39;00m\u001B[38;5;250m \u001B[39m\u001B[38;5;28;01mNone\u001B[39;00m\n\u001B[32m   1326\u001B[39m \u001B[38;5;28;01mexcept\u001B[39;00m \u001B[38;5;167;01mException\u001B[39;00m:\n\u001B[32m   1327\u001B[39m     \u001B[38;5;28mself\u001B[39m.log.warning(\u001B[33m\"\u001B[39m\u001B[33mInvalid Message:\u001B[39m\u001B[33m\"\u001B[39m, exc_info=\u001B[38;5;28;01mTrue\u001B[39;00m)\n",
      "\u001B[31mKeyboardInterrupt\u001B[39m: Interrupted by user"
     ]
    }
   ],
   "execution_count": 1
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
